version: '3.8'
services:
  traefik:
    image: traefik:v3.3.4
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --certificatesresolvers.myresolver.acme.caserver=https://djenkoit.fr/acme/acme/directory
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=admin@djenkoit.fr
      - --certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LEGO_CA_CERTIFICATES=/etc/traefik/certs/root.crt
      - TZ=Europe/Paris
    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/etc/traefik/acme.json
      - ./traefik/certs:/etc/traefik/certs:ro
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dashboard.djenkoit.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      # Ajout d'une authentification basique
#      - "traefik.http.routers.traefik.middlewares=traefik-auth"
#      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$ruca84Hq$$mbjdMZBAG.KWn7vfN/SNK/"

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app1.djenkoit.fr`)"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.entrypoints=websecure"
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: bridge
    name: traefik-network
